### ISSUE TITLE
Collaborative work

### ISSUE THREAD

**Issue by miyamot0** [eQualityTime/CommuniKate#2]
Hi Joe,

I'm currently working on a similar project.  I had explored a hybrid app approach to SGD AAC, initially due to compatibility, but have since expanded native solutions to the same effect using Xamarin and its fork of the Cocos2d engine for visuals.

My active git of this project is https://github.com/miyamot0/FastTalker if you might want to consider native, crossplatform approaches to SGD AAC.

I'm pleased to see more open source approaches to this type of work-- are you aware of anyone else doing this work?

**Comment by joereddington** [comment]
Closing - @miyamot0 are having a productive email conversation and I'm doing some testing on  https://github.com/miyamot0/FastTalker
