### ISSUE TITLE
Communicate V3 Release 

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/CommuniKate#5]
What needs to happen? 

* New code has to be written
* New Communicate Templates have to work with new code. 
* New Manual has to be written. 

So this mostly depends on another issue, that issue should be ahead of this one.

**Comment by joereddington-public** [comment]
What needs to happen? 

* New code has to be written
* New Communicate Templates have to work with new code. 
* New Manual has to be written.

**Comment by joereddington** [comment]
This depends on Public/issues/111

**Comment by joereddington** [comment]
I don't think it does - I'm currently trying to get hold of the new files...
